mod commands;

use tauri::Manager;

fn uuid_v4() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.subsec_nanos())
        .unwrap_or(0);
    let pid = std::process::id();
    format!("{:x}{:x}{:x}", nanos, pid, nanos ^ pid)
}

pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .setup(|app| {
            #[cfg(not(debug_assertions))]
            {
                let handle = app.handle().clone();

                let app_data_dir = handle
                    .path()
                    .app_data_dir()
                    .expect("cannot resolve app data dir");
                std::fs::create_dir_all(&app_data_dir).ok();

                let db_url = format!(
                    "file:{}",
                    app_data_dir.join("data.db").to_str().unwrap_or("data.db")
                );

                let resource_dir = handle
                    .path()
                    .resource_dir()
                    .expect("cannot resolve resource dir");
                let server_js = resource_dir
                    .join("resources")
                    .join("standalone")
                    .join("server.js");

                let secret_path = app_data_dir.join("secret.key");
                let nextauth_secret = if secret_path.exists() {
                    std::fs::read_to_string(&secret_path).unwrap_or_else(|_| uuid_v4())
                } else {
                    let s = uuid_v4();
                    std::fs::write(&secret_path, &s).ok();
                    s
                };

                std::thread::spawn(move || {
                    let mut child = std::process::Command::new("node")
                        .arg(server_js)
                        .env("PORT", "3000")
                        .env("HOSTNAME", "127.0.0.1")
                        .env("NODE_ENV", "production")
                        .env("APP_MODE", "desktop")
                        .env("DATABASE_URL", &db_url)
                        .env("DATABASE_AUTH_TOKEN", "")
                        .env("NEXTAUTH_SECRET", &nextauth_secret)
                        .env("NEXTAUTH_URL", "http://127.0.0.1:3000")
                        .spawn()
                        .expect("Failed to start Next.js server — ensure Node.js is installed");
                    child.wait().ok();
                });
            }

            Ok(())
        })
        // Reference command functions through their submodules so the macro-generated
        // metadata (generated by #[tauri::command]) stays in scope.
        .invoke_handler(tauri::generate_handler![
            commands::printer::list_printers,
            commands::system::get_app_data_path,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
